image: node:6

stages:
  - build
  - test

install_dependencies:
    stage: build
    script: npm install
    artifacts:
        paths: ["node_modules"]
  
run_build:
    stage: build
    script: npm run build
  
run_tests:
  stage: test
  script: npm test
