image: node:6

stages:
  - build
  - test

install_dependencies:
    stage: build
    script: npm install
  
run_build:
    stage: build
    script: node_modules/.bin/webpack
  
run_tests:
  stage: test
  script: npm test
